### ISSUE TITLE
Good idea!

### ISSUE THREAD

**Issue by gtamborero** [MadnessLabs/StencilPress#1]
Hi Madness! The idea is great. I have tried to install StencilPress but I see it's dependent of Sage (a few years ago I tested Sage and it's a very good starter theme for developers)... but! What I think it would be a good idea about Wordpress and Stencil is to merge them outside the theme; so you can use any theme but use Web Components. Maybe a plugin is a good solution ;) I'm working arround it and maybe will do it. Let's keep in touch if you want ;)

**Comment by popcorn245** [comment]
Love your idea Guillermo! Have wanted to circle back to this project eventually. I am using so little of roots (Sage) that it didn't make a whole lot of sense. We will be working on getting components working via a plugin on WordPress and would love to collab on it. Thanks for reaching out and look forward to hearing from you soon! ^_^

--- original message ---
On July 27, 2019, 6:05 PM CDT notifications@github.com wrote:


Hi Madness! The idea is great. I have tried to install StencilPress but I see it's dependent of Sage (a few years ago I tested Sage and it's a very good starter theme for developers)... but! What I think it would be a good idea about Wordpress and Stencil is to merge them outside the theme; so you can use any theme but use Web Components. Maybe a plugin is a good solution ;) I'm working arround it and maybe will do it. Let's keep in touch if you want ;)

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by popcorn245** [comment]
Going to close this out but @gtamborero I am curious if you made any progress yourself on this?

**Comment by gtamborero** [comment]
Thanks @popcorn245 ! Didn't do anything more about stencil. I'm working with WordPress ACF Plugin using blocks and it's the most similar approach to use webcomponents but without using them. So no webcomponents but WordPress blocks build easily. There's a similar plugin (Genesis Blocks) that does the same thing. One year ago I did an explanation on a WordCamp (spain): https://www.youtube.com/watch?v=wWs1zmOYfCc

Thanks!
